# Generated by Django 4.1.1 on 2023-01-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0002_newmebelimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='MebelCategoryModel',
        ),
        migrations.AlterModelOptions(
            name='mebelcategorymodel',
            options={'verbose_name': 'Mebel_Category', 'verbose_name_plural': 'Mebel_Categories'},
        ),
    ]
