# Generated by Django 4.1.1 on 2023-01-06 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mebel', '0003_rename_categorymodel_mebelcategorymodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mebelmodel',
            name='creater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mebels', to=settings.AUTH_USER_MODEL),
        ),
    ]
