# Generated by Django 4.1.1 on 2023-01-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0004_mebelmodel_creater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mebelmodel',
            old_name='creater',
            new_name='creator',
        ),
    ]
