# Generated by Django 4.1.1 on 2023-01-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0005_rename_creater_mebelmodel_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mebelmodel',
            old_name='descriptions',
            new_name='long_descriptions',
        ),
        migrations.AddField(
            model_name='mebelmodel',
            name='short_descriptions',
            field=models.TextField(null=True, verbose_name='short_descriptions'),
        ),
    ]
