# Generated by Django 4.1.1 on 2023-01-06 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0108_alter_userwishlistmodel_options'),
        ('mebel', '0006_rename_descriptions_mebelmodel_long_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mebelmodel',
            name='price',
            field=models.IntegerField(max_length=50, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='mebelmodel',
            name='price_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_types_mebel', to='products.pricelistmodel'),
        ),
    ]
