# Generated by Django 4.1.1 on 2023-01-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0007_mebelmodel_price_mebelmodel_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mebelmodel',
            name='price',
            field=models.IntegerField(null=True, verbose_name='price'),
        ),
    ]
