# Generated by Django 4.1.1 on 2023-01-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0009_alter_mebelmodel_long_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='mebelmodel',
            name='phone_number',
            field=models.IntegerField(null=True, verbose_name='phone_number'),
        ),
        migrations.AddField(
            model_name='mebelmodel',
            name='web_address_latitude',
            field=models.FloatField(null=True, verbose_name='web_address_latitude'),
        ),
        migrations.AddField(
            model_name='mebelmodel',
            name='web_address_longtitude',
            field=models.FloatField(null=True, verbose_name='web_address_longtitude'),
        ),
        migrations.AddField(
            model_name='mebelmodel',
            name='web_address_title',
            field=models.CharField(max_length=400, null=True, verbose_name='web_address_title'),
        ),
    ]
