# Generated by Django 4.1.1 on 2023-01-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0010_mebelmodel_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mebelmodel',
            name='draft',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
