# Generated by Django 4.1.5 on 2023-03-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0013_mebelmodel_isbookmarked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mebelmodel',
            name='phone_number',
            field=models.CharField(max_length=30, null=True, verbose_name='phone_number'),
        ),
    ]
