# Generated by Django 4.1.5 on 2023-07-25 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mebel', '0015_alter_mebelmodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mebelmodel',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mebels', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
    ]
