# Generated by Django 4.1.5 on 2023-09-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0016_alter_mebelmodel_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='mebelcategorymodel',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='mebelcategorymodel',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='mebelmodel',
            name='long_descriptions_ru',
            field=models.TextField(null=True, verbose_name='descriptions'),
        ),
        migrations.AddField(
            model_name='mebelmodel',
            name='long_descriptions_uz',
            field=models.TextField(null=True, verbose_name='descriptions'),
        ),
        migrations.AddField(
            model_name='mebelmodel',
            name='short_descriptions_ru',
            field=models.TextField(null=True, verbose_name='short_descriptions'),
        ),
        migrations.AddField(
            model_name='mebelmodel',
            name='short_descriptions_uz',
            field=models.TextField(null=True, verbose_name='short_descriptions'),
        ),
        migrations.AddField(
            model_name='mebelmodel',
            name='title_ru',
            field=models.CharField(max_length=400, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='mebelmodel',
            name='title_uz',
            field=models.CharField(max_length=400, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='mebelmodel',
            name='web_address_title_ru',
            field=models.CharField(max_length=400, null=True, verbose_name='web_address_title'),
        ),
        migrations.AddField(
            model_name='mebelmodel',
            name='web_address_title_uz',
            field=models.CharField(max_length=400, null=True, verbose_name='web_address_title'),
        ),
    ]
