# Generated by Django 4.0 on 2022-12-12 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_alter_customuser_groups_and_more'),
        ('products', '0082_howsalemodel_alter_housemodel_how_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'Store_amenities',
                'verbose_name_plural': 'Store_amenities',
            },
        ),
        migrations.CreateModel(
            name='UseForModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'Для',
                'verbose_name_plural': 'Для',
            },
        ),
        migrations.CreateModel(
            name='StoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='store_images', verbose_name='image')),
                ('brand_image', models.ImageField(null=True, upload_to='avatar_image', verbose_name='brand_image')),
                ('brand', models.CharField(max_length=200, null=True, verbose_name='brand')),
                ('price', models.PositiveIntegerField(null=True, verbose_name='price')),
                ('phoneNumber', models.PositiveIntegerField(verbose_name='phoneNumber')),
                ('address', models.CharField(max_length=400, null=True, verbose_name='address')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('isBookmarked', models.BooleanField(default=False, verbose_name='isBookmarked')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('draft', models.BooleanField(default=False)),
                ('product_status', models.IntegerField(choices=[(0, 'InProgress'), (1, 'PUBLISH'), (2, 'DELETED'), (3, 'ARCHIVED'), (4, 'REJECTED')], default=0, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='user.customuser')),
                ('price_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_price_type', to='products.pricelistmodel')),
                ('store_amenitites', models.ManyToManyField(to='store.StoreAmenities', verbose_name='store_amenities')),
                ('use_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.useformodel')),
            ],
            options={
                'verbose_name': 'Обустройствo дома',
                'verbose_name_plural': 'Обустройствo дома',
                'ordering': ['-id'],
            },
        ),
    ]
