# Generated by Django 4.0 on 2022-12-16 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowStoreServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True, verbose_name='Какая услуга')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'Как продавать',
                'verbose_name_plural': 'Как продавать',
            },
        ),
        migrations.AddField(
            model_name='storemodel',
            name='how_store_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.howstoreservicemodel'),
        ),
    ]
