# Generated by Django 4.0 on 2022-12-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_howstoreservicemodel_storemodel_how_store_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemodel',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
