# Generated by Django 4.0 on 2022-12-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_storemodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storemodel',
            name='slug',
        ),
    ]
