# Generated by Django 4.0 on 2022-12-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_storemodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemodel',
            name='view_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
