# Generated by Django 4.0 on 2022-12-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_storemodel_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemodel',
            name='store_amenitites',
            field=models.ManyToManyField(related_name='store_amenitites', to='store.StoreAmenities', verbose_name='store_amenities'),
        ),
    ]
