# Generated by Django 4.1.1 on 2022-12-30 12:01

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_storemodel_store_amenitites'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemodel',
            name='youtube_video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
