# Generated by Django 4.1.1 on 2023-01-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_storemodel_youtube_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storemodel',
            name='youtube_video',
        ),
        migrations.AddField(
            model_name='storemodel',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
