# Generated by Django 4.1.1 on 2023-01-05 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_storemodel_youtube_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreBrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Бренд')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.RemoveField(
            model_name='storemodel',
            name='brand',
        ),
        migrations.AddField(
            model_name='storemodel',
            name='brand_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.storebrandmodel'),
        ),
    ]
