# Generated by Django 4.1.5 on 2023-03-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_storebrandmodel_remove_storemodel_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemodel',
            name='phoneNumber',
            field=models.IntegerField(max_length=20, verbose_name='phoneNumber'),
        ),
    ]
