# Generated by Django 4.1.5 on 2023-03-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_storemodel_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemodel',
            name='phoneNumber',
            field=models.IntegerField(default=0, verbose_name='phoneNumber'),
        ),
    ]
