# Generated by Django 4.1.5 on 2023-03-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_storemodel_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemodel',
            name='phoneNumber',
            field=models.CharField(max_length=25, verbose_name='phoneNumber'),
        ),
    ]
