# Generated by Django 4.1.5 on 2023-04-07 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0112_alter_housemodel_app_ipoteka_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0013_alter_storemodel_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemodel',
            name='brand_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.storebrandmodel', verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='draft'),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='how_store_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.howstoreservicemodel', verbose_name='how_store'),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='price_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_price_type', to='products.pricelistmodel', verbose_name='price_type'),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='product_status',
            field=models.IntegerField(choices=[(0, 'InProgress'), (1, 'PUBLISH'), (2, 'DELETED'), (3, 'ARCHIVED'), (4, 'REJECTED')], default=0, null=True, verbose_name='product status'),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='use_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.useformodel', verbose_name='use_for'),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='view_count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='view_count'),
        ),
    ]
