# Generated by Django 4.1.5 on 2023-09-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_storebrandmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='howstoreservicemodel',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Какая услуга'),
        ),
        migrations.AddField(
            model_name='howstoreservicemodel',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Какая услуга'),
        ),
        migrations.AddField(
            model_name='storeamenities',
            name='title_ru',
            field=models.CharField(max_length=90, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='storeamenities',
            name='title_uz',
            field=models.CharField(max_length=90, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='useformodel',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='useformodel',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
    ]
