# Generated by Django 4.1.5 on 2023-09-13 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_storemodel_address_ru_storemodel_address_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storemodel',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='storemodel',
            name='address_uz',
        ),
    ]
