# Generated by Django 4.1.5 on 2023-07-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0002_alter_carouselmodel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerADSModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='banner_ads/images', verbose_name='banner_ads_image')),
                ('url', models.URLField(max_length=250, verbose_name='url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'Banner_ads',
                'verbose_name_plural': 'Banner_ads',
            },
        ),
    ]
