 alias pmr="python manage.py runserver"
 alias pmc="python manage.py collectstatic"
 alias pmmk="python manage.py makemigrations"
 alias pmm="python manage.py migrate"
 alias pmcu="python manage.py createsuperuser"