# Generated by Django 4.1.1 on 2022-10-04 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0020_remove_mastermodel_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='master_images', verbose_name='image')),
            ],
            options={
                'verbose_name': 'master_image',
                'verbose_name_plural': 'master_images',
            },
        ),
        migrations.CreateModel(
            name='MasterProfessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'profession',
                'verbose_name_plural': 'professions',
            },
        ),
        migrations.CreateModel(
            name='MasterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='master_image', verbose_name='image')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.PositiveIntegerField(verbose_name='phone')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('avatar', models.FileField(upload_to='master_avatar', verbose_name='avatar')),
                ('descriptions', models.TextField(verbose_name='descriptions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.mapmodel', verbose_name='address')),
                ('images', models.ManyToManyField(blank=True, to='masters.masterimagesmodel', verbose_name='images')),
                ('profession', models.ManyToManyField(blank=True, to='masters.masterprofessionmodel', verbose_name='profession')),
            ],
        ),
    ]
