# Generated by Django 4.1.1 on 2022-10-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermodel',
            name='experience',
            field=models.IntegerField(null=True, verbose_name='experience'),
        ),
    ]
