# Generated by Django 4.1.1 on 2022-10-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_mastermodel_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastermodel',
            options={'verbose_name': 'Master', 'verbose_name_plural': 'Masters'},
        ),
    ]
