# Generated by Django 4.1.1 on 2022-10-22 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0006_mastermodel_isbookmarked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastermodel',
            options={'ordering': ['-id'], 'verbose_name': 'Master', 'verbose_name_plural': 'Masters'},
        ),
        migrations.AddField(
            model_name='mastermodel',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mastermodel',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastermodel',
            name='product_status',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('PUBLISH', 'PUBLISH'), ('DELETED', 'DELETED'), ('ARCHIVED', 'ARCHIVED'), ('REJECTED', 'REJECTED')], default=('PUBLISH', 'PUBLISH'), max_length=30, null=True),
        ),
    ]
