# Generated by Django 4.1.1 on 2022-10-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_alter_mastermodel_options_mastermodel_draft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermodel',
            name='product_status',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('PUBLISH', 'PUBLISH'), ('DELETED', 'DELETED'), ('ARCHIVED', 'ARCHIVED'), ('REJECTED', 'REJECTED')], default=('InProgress', 'InProgress'), max_length=30, null=True),
        ),
    ]
