# Generated by Django 4.1.1 on 2022-10-22 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0008_alter_mastermodel_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maklers', to=settings.AUTH_USER_MODEL),
        ),
    ]
