# Generated by Django 4.1.1 on 2022-10-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_alter_mastermodel_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterimagesmodel',
            options={'verbose_name': 'Изображения для мастера', 'verbose_name_plural': 'Изображения для мастеров'},
        ),
        migrations.AlterModelOptions(
            name='mastermodel',
            options={'ordering': ['-id'], 'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастеры'},
        ),
        migrations.AlterModelOptions(
            name='masterprofessionmodel',
            options={'verbose_name': 'Профессия', 'verbose_name_plural': 'Профессии'},
        ),
    ]
