# Generated by Django 4.1.1 on 2022-11-22 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_alter_masterimagesmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastermodel',
            name='images',
        ),
        migrations.AddField(
            model_name='masterimagesmodel',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='masters.mastermodel'),
            preserve_default=False,
        ),
    ]
