# Generated by Django 4.1.1 on 2022-11-22 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0011_remove_mastermodel_images_masterimagesmodel_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maklers', to=settings.AUTH_USER_MODEL),
        ),
    ]
