# Generated by Django 4.1.1 on 2022-11-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_remove_masterimagesmodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterimagesmodel',
            name='images',
            field=models.FileField(null=True, upload_to='master_images'),
        ),
    ]
