# Generated by Django 4.1.1 on 2022-11-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0014_alter_masterimagesmodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermodel',
            name='image',
            field=models.FileField(upload_to='master_image'),
        ),
    ]
