# Generated by Django 4.1.2 on 2022-12-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_remove_mastermodel_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastermodel',
            name='image',
        ),
    ]
