# Generated by Django 3.2.16 on 2022-12-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0017_remove_mastermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermodel',
            name='product_status',
            field=models.IntegerField(choices=[(0, 'InProgress'), (1, 'PUBLISH'), (2, 'DELETED'), (3, 'ARCHIVED'), (4, 'REJECTED')], default=(0, 'InProgress'), null=True),
        ),
    ]
