# Generated by Django 4.0 on 2022-12-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0019_alter_mastermodel_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermodel',
            name='profession',
            field=models.ManyToManyField(blank=True, related_name='profession', to='masters.MasterProfessionModel', verbose_name='profession'),
        ),
    ]
