# Generated by Django 4.0 on 2022-12-17 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_groups_and_more'),
        ('masters', '0021_howservicemodel_mastermodel_how_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterUserWishlistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.mastermodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customuser')),
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'Wishlist',
            },
        ),
    ]
