# Generated by Django 4.0 on 2022-12-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0022_masteruserwishlistmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermodel',
            name='avatar',
            field=models.FileField(null=True, upload_to='master_avatar', verbose_name='avatar'),
        ),
    ]
