# Generated by Django 4.0 on 2022-12-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0024_alter_mastermodel_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermodel',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
