# Generated by Django 4.0 on 2022-12-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0026_remove_mastermodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermodel',
            name='view_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
