# Generated by Django 4.1.1 on 2022-12-30 12:01

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0027_mastermodel_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermodel',
            name='youtube_video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
