# Generated by Django 4.1.1 on 2023-01-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0031_remove_mastermodel_youtube_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastermodel',
            name='youtube_link',
        ),
    ]
