# Generated by Django 4.1.5 on 2023-03-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0033_alter_mastermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermodel',
            name='phone',
            field=models.CharField(default=0, max_length=30, verbose_name='phone'),
        ),
    ]
