# Generated by Django 4.1.5 on 2023-04-07 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0034_alter_mastermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterimagesmodel',
            name='images',
            field=models.FileField(null=True, upload_to='master_images', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='masterimagesmodel',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='masters.mastermodel', verbose_name='мастер'),
        ),
        migrations.AlterField(
            model_name='mastermodel',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='draft'),
        ),
        migrations.AlterField(
            model_name='mastermodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maklers', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='mastermodel',
            name='product_status',
            field=models.IntegerField(choices=[(0, 'InProgress'), (1, 'PUBLISH'), (2, 'DELETED'), (3, 'ARCHIVED'), (4, 'REJECTED')], default=0, help_text='Не трогать', null=True),
        ),
        migrations.AlterField(
            model_name='mastermodel',
            name='view_count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='view_count'),
        ),
    ]
