# Generated by Django 4.1.5 on 2023-09-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0035_alter_masterimagesmodel_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='howservicemodel',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Какая услуга'),
        ),
        migrations.AddField(
            model_name='howservicemodel',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Какая услуга'),
        ),
        migrations.AddField(
            model_name='mastermodel',
            name='address_title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='address_title'),
        ),
        migrations.AddField(
            model_name='mastermodel',
            name='address_title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='address_title'),
        ),
        migrations.AddField(
            model_name='mastermodel',
            name='descriptions_ru',
            field=models.TextField(null=True, verbose_name='descriptions'),
        ),
        migrations.AddField(
            model_name='mastermodel',
            name='descriptions_uz',
            field=models.TextField(null=True, verbose_name='descriptions'),
        ),
        migrations.AddField(
            model_name='mastermodel',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='mastermodel',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='masterprofessionmodel',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='masterprofessionmodel',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
    ]
