# Generated by Django 4.1.5 on 2023-09-13 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0036_howservicemodel_title_ru_howservicemodel_title_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastermodel',
            name='address_title_ru',
        ),
        migrations.RemoveField(
            model_name='mastermodel',
            name='address_title_uz',
        ),
    ]
