# Generated by Django 4.1.1 on 2022-10-21 13:49

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', user.models.MyUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
