# Generated by Django 4.1.1 on 2022-12-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mycode',
            field=models.IntegerField(null=True),
        ),
    ]
