# Generated by Django 4.1.1 on 2023-01-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_customuser_mycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
