# Generated by Django 4.1.5 on 2023-07-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_customuser_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mycode',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
