# Generated by Django 4.1.5 on 2023-07-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_customuser_mycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mycode',
            field=models.IntegerField(null=True),
        ),
    ]
