# Generated by Django 4.1.5 on 2023-07-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_customuser_balances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='balances',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='invited_by',
        ),
    ]
