# Generated by Django 4.1.5 on 2023-07-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_customuser_balances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referrer_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
