# Generated by Django 4.1.5 on 2023-07-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_customuser_balances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='referrer_link',
        ),
    ]
