# Generated by Django 4.1.5 on 2023-07-20 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_remove_customuser_invited_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
