# Generated by Django 4.1.5 on 2023-11-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_customuser_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
