# Generated by Django 4.1.1 on 2022-09-18 19:25

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600, verbose_name='title')),
                ('descriptions', models.TextField(verbose_name='descriptions')),
                ('price', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('rent', 'Rent'), ('for_sale', 'For_sale')], default=('for_sale', 'For_sale'), max_length=200)),
                ('rental_type', models.CharField(choices=[('long_time', 'Long_time'), ('several_months', 'Several_months'), ('daily', 'Daily')], default=('several_months', 'Several_months'), max_length=200)),
                ('object', models.CharField(choices=[('flat', 'Flat'), ('room', 'Room'), ('summer_cottage', 'Summer_cottage'), ('house', 'House'), ('part_house', 'Part_house'), ('townhouse', 'Townhouse'), ('bed_space', 'Bed_space')], default=None, max_length=200)),
                ('map', models.CharField(max_length=190, verbose_name='map')),
                ('image', models.FileField(upload_to='house_image', verbose_name='image')),
                ('general', models.CharField(max_length=90, verbose_name='general')),
                ('residential', models.CharField(max_length=90, verbose_name='residential')),
                ('number_of_rooms', models.CharField(max_length=30, verbose_name='number_of_rooms')),
                ('floor', models.CharField(max_length=30, verbose_name='floor')),
                ('floor_from', models.CharField(max_length=30, verbose_name='floor_from')),
                ('building_type', models.CharField(choices=[('brick', 'Brick'), ('monolith', 'Monolith'), ('panel', 'Panel'), ('blocky', 'Blocky')], default=None, max_length=50, verbose_name='building_type')),
                ('test_choices', multiselectfield.db.fields.MultiSelectField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categorymodel', verbose_name='category')),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
            },
        ),
    ]
