# Generated by Django 4.1.1 on 2022-09-18 19:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_housemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='test_choices',
            field=multiselectfield.db.fields.MultiSelectField(max_length=3, null=True),
        ),
    ]
