# Generated by Django 4.1.1 on 2022-09-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_housemodel_test_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemodel',
            name='test_choices',
        ),
    ]
