# Generated by Django 4.1.1 on 2022-09-22 14:47

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_amenitiesmodel_housemodel_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='master_image', verbose_name='image')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.PositiveIntegerField(verbose_name='phone')),
                ('password', models.IntegerField(verbose_name='password')),
                ('descriptions', models.TextField(verbose_name='descriptions')),
                ('my_field2', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Item title 2.1'), (2, 'Item title 2.2'), (3, 'Item title 2.3'), (4, 'Item title 2.4'), (5, 'Item title 2.5')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='amenities',
            field=models.ManyToManyField(blank=True, null=True, to='products.amenitiesmodel', verbose_name='amenities'),
        ),
    ]
