# Generated by Django 4.1.1 on 2022-09-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_mastermodel_alter_housemodel_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermodel',
            name='phone',
            field=models.CharField(max_length=60, verbose_name='phone'),
        ),
    ]
