# Generated by Django 4.1.1 on 2022-09-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_mastermodel_my_field2_mastermodel_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'Master_activity',
                'verbose_name_plural': 'Master_activities',
            },
        ),
        migrations.RemoveField(
            model_name='mastermodel',
            name='activity',
        ),
        migrations.AddField(
            model_name='mastermodel',
            name='activity',
            field=models.ManyToManyField(blank=True, to='products.masteractivity'),
        ),
    ]
