# Generated by Django 4.1.1 on 2022-09-29 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_masteractivity_remove_mastermodel_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressName', models.CharField(max_length=200, verbose_name='address')),
                ('latitude', models.FloatField(max_length=100, verbose_name='latitude')),
                ('longtitude', models.FloatField(max_length=100, verbose_name='longtitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Map',
                'verbose_name_plural': 'Maps',
            },
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='price',
            field=models.CharField(max_length=100, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.mapmodel', verbose_name='map'),
        ),
    ]
