# Generated by Django 4.1.1 on 2022-09-29 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_mapmodel_alter_housemodel_price_alter_housemodel_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.mapmodel', verbose_name='map'),
        ),
    ]
