# Generated by Django 4.1.1 on 2022-09-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_housemodel_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='isBookmarked',
            field=models.BooleanField(default=False, verbose_name='isBookmarked'),
        ),
    ]
