# Generated by Django 4.1.1 on 2022-09-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_houseimagemodel_remove_housemodel_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='houseimagemodel',
            options={'verbose_name': 'house_image', 'verbose_name_plural': 'house_images'},
        ),
    ]
