# Generated by Django 4.1.1 on 2022-09-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_houseimagemodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='products.amenitiesmodel', verbose_name='amenities'),
        ),
    ]
