# Generated by Django 4.1.1 on 2022-10-04 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_housemodel_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermodel',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.mapmodel', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='mapmodel',
            name='latitude',
            field=models.FloatField(verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='mapmodel',
            name='longtitude',
            field=models.FloatField(verbose_name='longtitude'),
        ),
    ]
