# Generated by Django 4.1.1 on 2022-10-19 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_housemodel_image_houseimagemodel_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimagemodel',
            name='property_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.housemodel'),
        ),
    ]
