# Generated by Django 4.1.1 on 2022-10-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_houseimagemodel_property_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseimagemodel',
            name='property_id',
        ),
        migrations.AddField(
            model_name='housemodel',
            name='images',
            field=models.FileField(null=True, upload_to='house_images', verbose_name='image'),
        ),
    ]
