# Generated by Django 4.1.1 on 2022-10-19 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_remove_houseimagemodel_property_id_housemodel_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseimagemodel',
            name='property_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pr_images', to='products.housemodel'),
        ),
    ]
