# Generated by Django 4.1.1 on 2022-10-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_houseimagemodel_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='images',
            field=models.FileField(default=1, null=True, upload_to='house_images', verbose_name='image'),
        ),
    ]
