# Generated by Django 4.1.1 on 2022-10-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_housemodel_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_test_image')),
            ],
        ),
        migrations.RemoveField(
            model_name='housemodel',
            name='images',
        ),
        migrations.AddField(
            model_name='housemodel',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='products.imagesmodel'),
        ),
    ]
