# Generated by Django 4.1.1 on 2022-10-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_imagesmodel_remove_housemodel_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesmodel',
            name='image',
            field=models.FileField(null=True, upload_to='house_test_image'),
        ),
    ]
