# Generated by Django 4.1.1 on 2022-10-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_imagesmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemodel',
            name='images',
        ),
        migrations.AddField(
            model_name='housemodel',
            name='images',
            field=models.FileField(default=1, upload_to='house_test_image'),
            preserve_default=False,
        ),
    ]
