# Generated by Django 4.1.1 on 2022-10-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_remove_housemodel_images_housemodel_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemodel',
            name='images',
        ),
        migrations.AddField(
            model_name='housemodel',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='products.imagesmodel'),
        ),
    ]
