# Generated by Django 4.1.1 on 2022-10-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_housemodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemodel',
            name='archive',
        ),
        migrations.AddField(
            model_name='housemodel',
            name='product_status',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('PUBLISH', 'PUBLISH'), ('DELETED', 'DELETED'), ('ARCHIVED', 'ARCHIVED'), ('REJECTED', 'REJECTED')], default=('PUBLISH', 'PUBLISH'), max_length=30, null=True),
        ),
    ]
