# Generated by Django 4.1.1 on 2022-10-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_alter_housemodel_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemodel',
            name='creator',
        ),
    ]
