# Generated by Django 4.1.1 on 2022-10-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_housemodel_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemodel',
            name='creator',
        ),
    ]
