# Generated by Django 4.1.1 on 2022-10-25 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0041_alter_housemodel_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenitiesmodel',
            options={'verbose_name': 'Все удобства', 'verbose_name_plural': 'Все удобства'},
        ),
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='houseimagemodel',
            options={'verbose_name': 'Изображения маклер (квартиры и т.д)', 'verbose_name_plural': 'Изображения маклер (квартиры и т.д)'},
        ),
        migrations.AlterModelOptions(
            name='housemodel',
            options={'ordering': ['-id'], 'verbose_name': 'Маклер, (квартиры и т.д)', 'verbose_name_plural': 'Маклер, (квартиры и т.д)'},
        ),
        migrations.AlterModelOptions(
            name='mapmodel',
            options={'verbose_name': 'Карта', 'verbose_name_plural': 'Карты'},
        ),
        migrations.AddField(
            model_name='housemodel',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
