# Generated by Django 4.1.1 on 2022-10-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_alter_amenitiesmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenitiesmodel',
            name='image',
            field=models.FileField(default=1, upload_to='amenities_images'),
            preserve_default=False,
        ),
    ]
