# Generated by Django 4.1.1 on 2022-10-31 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_housemodel_web_building_type_housemodel_web_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemodel',
            name='images',
        ),
        migrations.CreateModel(
            name='NewHouseImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(null=True, upload_to='API/images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.housemodel')),
            ],
        ),
    ]
