# Generated by Django 4.1.1 on 2022-11-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_remove_housemodel_images_newhouseimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimagemodel',
            name='image',
            field=models.ImageField(upload_to='house_images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='newhouseimages',
            name='images',
            field=models.ImageField(null=True, upload_to='API/images'),
        ),
    ]
