# Generated by Django 4.1.1 on 2022-11-05 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_remove_pricelistmodel_product_housemodel_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='price_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_types', to='products.pricelistmodel'),
        ),
    ]
