# Generated by Django 4.1.1 on 2022-11-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_alter_housemodel_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='pr_amenities', to='products.amenitiesmodel', verbose_name='amenities'),
        ),
        migrations.AlterField(
            model_name='pricelistmodel',
            name='price',
            field=models.CharField(max_length=10, null=True, verbose_name='price'),
        ),
    ]
