# Generated by Django 4.1.1 on 2022-11-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_housemodel_web_address_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='web_address_latitude',
            field=models.FloatField(null=True, verbose_name='web_address_latitude'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='web_address_longtitude',
            field=models.FloatField(null=True, verbose_name='web_address_longtitude'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='web_address_title',
            field=models.CharField(max_length=400, null=True, verbose_name='web_address_title'),
        ),
    ]
