# Generated by Django 4.1.1 on 2022-11-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_alter_housemodel_web_address_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='currency',
            field=models.CharField(max_length=10, null=True, verbose_name='app_currency'),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='typeOf',
            field=models.CharField(max_length=150, null=True, verbose_name='typeOf'),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='typeOfHouse',
            field=models.CharField(max_length=200, null=True, verbose_name='typeOfHouse'),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='type_t',
            field=models.CharField(max_length=90, null=True, verbose_name='type_t'),
        ),
    ]
