# Generated by Django 4.1.1 on 2022-11-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_housemodel_currency_housemodel_typeof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemodel',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='housemodel',
            name='typeOf',
        ),
        migrations.RemoveField(
            model_name='housemodel',
            name='typeOfHouse',
        ),
        migrations.RemoveField(
            model_name='housemodel',
            name='type_t',
        ),
    ]
