# Generated by Django 4.1.1 on 2022-11-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_remove_housemodel_currency_remove_housemodel_typeof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='app_price_type',
            field=models.CharField(default=1, max_length=10, verbose_name='app_price_type'),
            preserve_default=False,
        ),
    ]
