# Generated by Django 4.1.1 on 2022-11-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_housemodel_app_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='app_ipoteka',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='app_mebel',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='app_type',
            field=models.CharField(max_length=80, null=True, verbose_name='app_type'),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='typeOfHouse',
            field=models.CharField(max_length=90, null=True, verbose_name='typeOfHouse'),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='typeOfObject',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='typeOfRent',
            field=models.CharField(max_length=90, null=True, verbose_name='typeOfRent'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='app_price_type',
            field=models.CharField(max_length=10, null=True, verbose_name='app_price_type'),
        ),
    ]
