# Generated by Django 4.1.1 on 2022-11-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0060_housemodel_app_ipoteka_housemodel_app_mebel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemodel',
            name='app_price_type',
        ),
        migrations.AddField(
            model_name='housemodel',
            name='app_currency',
            field=models.CharField(max_length=10, null=True, verbose_name='app_currency'),
        ),
    ]
