# Generated by Django 4.1.1 on 2022-11-15 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_remove_housemodel_app_price_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='price_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_types', to='products.pricelistmodel'),
        ),
    ]
