# Generated by Django 4.1.1 on 2022-11-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0062_alter_housemodel_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='phone_number',
            field=models.CharField(max_length=19, null=True, verbose_name='phone_number'),
        ),
    ]
