# Generated by Django 4.1.1 on 2022-11-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_housemodel_app_new_building'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housemodel',
            old_name='web_type',
            new_name='pm_general',
        ),
        migrations.RenameField(
            model_name='housemodel',
            old_name='web_object',
            new_name='pm_kitchen',
        ),
        migrations.RenameField(
            model_name='housemodel',
            old_name='web_rental_type',
            new_name='pm_residential',
        ),
    ]
