# Generated by Django 4.1.1 on 2022-11-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0066_rename_web_type_housemodel_pm_general_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='pm_general',
            field=models.CharField(max_length=400, null=True, verbose_name='pm_residential'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='pm_residential',
            field=models.CharField(max_length=500, null=True, verbose_name='pm_kitchen'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='web_address_longtitude',
            field=models.FloatField(null=True, verbose_name='pm_general'),
        ),
    ]
