# Generated by Django 4.1.1 on 2022-11-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0069_housemodel_web_rental_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='web_object',
            field=models.CharField(max_length=400, null=True, verbose_name='web_object'),
        ),
    ]
