# Generated by Django 3.2.16 on 2022-12-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0071_housemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='product_status',
            field=models.CharField(choices=[(0, 'InProgress'), (1, 'PUBLISH'), (2, 'DELETED'), (3, 'ARCHIVED'), (4, 'REJECTED')], default=(0, 'InProgress'), max_length=30, null=True),
        ),
    ]
