# Generated by Django 3.2.16 on 2022-12-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0074_alter_housemodel_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='pm_kitchen',
            field=models.CharField(max_length=300, null=True, verbose_name='pm_kitchen2'),
        ),
    ]
