# Generated by Django 3.2.16 on 2022-12-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0075_alter_housemodel_pm_kitchen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemodel',
            name='web_object',
        ),
    ]
