# Generated by Django 3.2.16 on 2022-12-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0076_remove_housemodel_web_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='draft',
            field=models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0, null=True),
        ),
    ]
