# Generated by Django 3.2.16 on 2022-12-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0079_alter_housemodel_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='subtitle',
            field=models.TextField(null=True, verbose_name='subtitle'),
        ),
    ]
