# Generated by Django 4.0 on 2022-12-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0084_alter_housemodel_web_address_longtitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='pm_general',
            field=models.CharField(max_length=400, null=True, verbose_name='pm_general'),
        ),
    ]
