# Generated by Django 4.0 on 2022-12-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0085_alter_housemodel_pm_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
