# Generated by Django 4.0 on 2022-12-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0088_remove_housemodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='view_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
