# Generated by Django 4.0 on 2022-12-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0092_houserentaltypemodel_housemodel_rental_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='houserentaltypemodel',
            options={'verbose_name': 'Тип маклера', 'verbose_name_plural': 'Тип маклера'},
        ),
        migrations.AlterModelOptions(
            name='housetypemodel',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
    ]
