# Generated by Django 4.0 on 2022-12-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0093_alter_houserentaltypemodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemodel',
            name='object',
        ),
    ]
