# Generated by Django 4.0 on 2022-12-23 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0094_remove_housemodel_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseObjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Обьект',
                'verbose_name_plural': 'Обьекты',
            },
        ),
        migrations.AddField(
            model_name='housemodel',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.houseobjectmodel'),
        ),
    ]
