# Generated by Django 4.0 on 2022-12-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0096_alter_housemodel_object_alter_housemodel_rental_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='object',
            field=models.CharField(blank=True, choices=[('квартиру', 'Flat'), ('комната', 'Room'), ('дача', 'Summer_cottage'), ('дома', 'House'), ('участка', 'Part_house'), ('townhouse', 'Townhouse'), ('bed_space', 'Bed_space')], default=None, max_length=200, null=True),
        ),
    ]
