# Generated by Django 4.1.1 on 2022-12-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0101_alter_housemodel_building_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='product_status',
            field=models.IntegerField(choices=[(0, 'InProgress'), (1, 'PUBLISH'), (2, 'DELETED'), (3, 'ARCHIVED'), (4, 'REJECTED')], default=(0, 'InProgress'), null=True),
        ),
    ]
