# Generated by Django 4.1.1 on 2023-01-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0107_remove_housemodel_youtube_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userwishlistmodel',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
    ]
