# Generated by Django 4.1.5 on 2023-04-06 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0108_alter_userwishlistmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='housemodel',
            name='app_currency',
        ),
        migrations.RemoveField(
            model_name='housemodel',
            name='app_type',
        ),
        migrations.RemoveField(
            model_name='housemodel',
            name='general',
        ),
        migrations.RemoveField(
            model_name='housemodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='housemodel',
            name='pm_kitchen',
        ),
        migrations.RemoveField(
            model_name='housemodel',
            name='residential',
        ),
        migrations.RemoveField(
            model_name='housemodel',
            name='typeOfHouse',
        ),
        migrations.RemoveField(
            model_name='housemodel',
            name='typeOfObject',
        ),
        migrations.RemoveField(
            model_name='housemodel',
            name='typeOfRent',
        ),
        migrations.RemoveField(
            model_name='housemodel',
            name='web_building_type',
        ),
        migrations.RemoveField(
            model_name='housemodel',
            name='web_rental_type',
        ),
        migrations.RemoveField(
            model_name='housemodel',
            name='web_type',
        ),
    ]
