# Generated by Django 4.1.5 on 2023-04-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0109_remove_housemodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='pm_kitchen',
            field=models.CharField(max_length=300, null=True, verbose_name='pm_kitchen2'),
        ),
    ]
