# Generated by Django 4.1.5 on 2023-04-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0110_housemodel_pm_kitchen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapModel',
        ),
        migrations.AlterField(
            model_name='amenitiesmodel',
            name='image',
            field=models.FileField(upload_to='amenities_images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='image',
            field=models.FileField(upload_to='category_image', verbose_name='image'),
        ),
    ]
