# Generated by Django 4.1.5 on 2023-04-07 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0111_delete_mapmodel_alter_amenitiesmodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='app_ipoteka',
            field=models.BooleanField(default=False, null=True, verbose_name='app_ipoteka'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='app_mebel',
            field=models.BooleanField(default=False, null=True, verbose_name='app_mebel'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='app_new_building',
            field=models.BooleanField(default=False, null=True, verbose_name='app_new_building'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='draft',
            field=models.BooleanField(default=False, null=True, verbose_name='draft'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='how_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.howsalemodel', verbose_name='how_sale'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='object',
            field=models.CharField(blank=True, choices=[('квартира', 'квартиру'), ('комната', 'комната'), ('дача', 'дача'), ('дома', 'дома'), ('участка', 'участка'), ('таунхаус', 'Townhouse'), ('спальное', 'Bed_space')], default=None, max_length=200, null=True, verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='pm_kitchen',
            field=models.CharField(max_length=300, null=True, verbose_name='pm_kitchens'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='pm_residential',
            field=models.CharField(max_length=500, null=True, verbose_name='pm_residential'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='price_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_types', to='products.pricelistmodel', verbose_name='price_type'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='product_status',
            field=models.IntegerField(choices=[(0, 'InProgress'), (1, 'PUBLISH'), (2, 'DELETED'), (3, 'ARCHIVED'), (4, 'REJECTED')], default=0, null=True, verbose_name='product status'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='property_type',
            field=models.CharField(choices=[('жилая', 'жилая'), ('коммерческая', 'коммерческая')], default=('коммерческая', 'коммерческая'), max_length=100, null=True, verbose_name='property_type'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='rental_type',
            field=models.CharField(blank=True, choices=[('длительно', 'Длительно'), ('несколько месяцев', 'несколько месяцев'), ('посуточно', 'посуточно')], default=('несколько месяцев', 'несколько месяцев'), max_length=200, null=True, verbose_name='rental_type'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='type',
            field=models.CharField(blank=True, choices=[('купить', 'Купить'), ('продать', 'Продать'), ('аденда', 'Аренда')], default=('продать', 'Продать'), max_length=200, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='view_count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='view count'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='youtube_link'),
        ),
        migrations.AlterField(
            model_name='newhouseimages',
            name='images',
            field=models.ImageField(null=True, upload_to='API/images', verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='newhouseimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.housemodel', verbose_name='product'),
        ),
    ]
