# Generated by Django 4.1.5 on 2023-04-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0112_alter_housemodel_app_ipoteka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='descriptions_ru',
            field=models.TextField(null=True, verbose_name='descriptions'),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='descriptions_uz',
            field=models.TextField(null=True, verbose_name='descriptions'),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='title_ru',
            field=models.CharField(max_length=600, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='title_uz',
            field=models.CharField(max_length=600, null=True, verbose_name='title'),
        ),
    ]
