# Generated by Django 4.1.5 on 2023-09-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0115_categorymodel_subtitle_ru_categorymodel_subtitle_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='web_address_title_ru',
            field=models.CharField(max_length=400, null=True, verbose_name='web_address_title'),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='web_address_title_uz',
            field=models.CharField(max_length=400, null=True, verbose_name='web_address_title'),
        ),
    ]
