# Generated by Django 4.1.5 on 2023-09-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0116_housemodel_web_address_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenitiesmodel',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='amenitiesmodel',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='howsalemodel',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Как продавать'),
        ),
        migrations.AddField(
            model_name='howsalemodel',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Как продавать'),
        ),
    ]
