# Generated by Django 4.1.5 on 2023-09-21 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0118_remove_housemodel_web_address_title_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasons', models.CharField(blank=True, choices=[('Товар продан', 'Товар продан'), ('Неверная цена', 'Неверная цена'), ('Объявление было размещено более одного раза', 'Объявление было размещено более одного раза'), ('Фото и информация в объявлении не совпадают', 'Фото и информация в объявлении не совпадают'), ('Адрес неверный', 'Адрес неверный'), ('Не могу сбросить звонок (звонки не отвечены)', 'Не могу сбросить звонок (звонки не отвечены)'), ('Запрещенные товары', 'Запрещенные товары'), ('Рекламодатель не является физическим лицом', 'Рекламодатель не является физическим лицом'), ('Мошенничество', 'Мошенничество'), ('Другая причина', 'Другая причина')], max_length=255, null=True, verbose_name='Причина')),
                ('reasons_ru', models.CharField(blank=True, choices=[('Товар продан', 'Товар продан'), ('Неверная цена', 'Неверная цена'), ('Объявление было размещено более одного раза', 'Объявление было размещено более одного раза'), ('Фото и информация в объявлении не совпадают', 'Фото и информация в объявлении не совпадают'), ('Адрес неверный', 'Адрес неверный'), ('Не могу сбросить звонок (звонки не отвечены)', 'Не могу сбросить звонок (звонки не отвечены)'), ('Запрещенные товары', 'Запрещенные товары'), ('Рекламодатель не является физическим лицом', 'Рекламодатель не является физическим лицом'), ('Мошенничество', 'Мошенничество'), ('Другая причина', 'Другая причина')], max_length=255, null=True, verbose_name='Причина')),
                ('reasons_uz', models.CharField(blank=True, choices=[('Товар продан', 'Товар продан'), ('Неверная цена', 'Неверная цена'), ('Объявление было размещено более одного раза', 'Объявление было размещено более одного раза'), ('Фото и информация в объявлении не совпадают', 'Фото и информация в объявлении не совпадают'), ('Адрес неверный', 'Адрес неверный'), ('Не могу сбросить звонок (звонки не отвечены)', 'Не могу сбросить звонок (звонки не отвечены)'), ('Запрещенные товары', 'Запрещенные товары'), ('Рекламодатель не является физическим лицом', 'Рекламодатель не является физическим лицом'), ('Мошенничество', 'Мошенничество'), ('Другая причина', 'Другая причина')], max_length=255, null=True, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тексты жалоб',
                'verbose_name_plural': 'Тексты жалоб',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_reason', models.TextField(blank=True, null=True, verbose_name='Другая причина')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints_house', to='products.housemodel')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.complaintmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Жалобы',
                'verbose_name_plural': 'Жалобы',
            },
        ),
        migrations.AddField(
            model_name='housemodel',
            name='complaints',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_complaints', to='products.complaint'),
        ),
    ]
