# Generated by Django 4.1.5 on 2023-09-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0118_remove_housemodel_web_address_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='type_ru',
            field=models.CharField(blank=True, choices=[('купить', 'Купить'), ('продать', 'Продать'), ('аденда', 'Аренда')], default=('продать', 'Продать'), max_length=200, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='type_uz',
            field=models.CharField(blank=True, choices=[('купить', 'Купить'), ('продать', 'Продать'), ('аденда', 'Аренда')], default=('продать', 'Продать'), max_length=200, null=True, verbose_name='type'),
        ),
    ]
