# Generated by Django 4.1.5 on 2023-09-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0119_housemodel_type_ru_housemodel_type_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemodel',
            name='type_ru',
        ),
        migrations.RemoveField(
            model_name='housemodel',
            name='type_uz',
        ),
    ]
